export const INCREMENT = 'INCREMENT';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const ARTICLE_NAME_FILTER = 'ARTICLE_NAME_FILTER';

export const ARTICLE_FILTER = 'ARTICLE_FILTER';

export const DATE_PERIOD_FILTER = 'DATE_PERIOD_FILTER';